server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: add-declaration-service
  profiles:
    active: ${PROFILE:local}
  jackson:
    time-zone: Europe/Tallinn

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.ee.declaration: ${LOG_LEVEL:info}

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /api-documentation.html

default-locale:
  locales:
    - language: en
      country: US
    - language: et
      country: EE